services:

  worker:
    image: onlyspans.worker.api
    build:
      context: ./src
      dockerfile: Onlyspans.Worker.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TargetsController__Endpoint: "http://targets-controller:8080"
      Kestrel__Endpoints__HttpEndpoint__Url: "http://+:8081"
      Kestrel__Endpoints__HttpEndpoint__Protocols: "Http1"
      Kestrel__Endpoints__Http2Endpoint__Url: "http://+:8080"
      Kestrel__Endpoints__Http2Endpoint__Protocols: "Http2"
    ports:
      - "5003:8080"
      - "5004:8081"
    networks:
      - developer-platform

networks:
  developer-platform:
    external: true
