services:

  worker:
    image: onlyspans.worker.api
    build:
      context: ./src
      dockerfile: Onlyspans.Worker.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TargetsController__Endpoint: "http://targets-controller:8080"
    ports:
      - "5003:8080"
    networks:
      - default
      - developer-platform

networks:
  developer-platform:
    external: true
